name: Test
on:
  workflow_dispatch
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-12 ]
    name: Simple test
    runs-on: ${{ matrix.os }}
    steps:

      - name: Set environment file
        id: environment-file
        run: |
            echo $RUNNER_OS
      - name: Set environment file
        run: |
            echo ${{ steps.environment-file.outputs }}
