name: Test
on:
  workflow_dispatch
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-12 ]
    name: Simple test
    runs-on: ${{ matrix.os }}
    steps:

      - name: Set environment file
        id: vars
        run: |
            echo "::set-output name=PLAT1::$RUNNER_OS"
            echo "::set-output name=PLAT2::$(uname)"
      - name: Set environment file
        run: |
            echo ${{ steps.vars.outputs.PLAT1 }}
            echo ${{ steps.vars.outputs.PLAT2 }}
